version: '3.8'
services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - pdf_storage:/app/data/pdfs
      - sqlite_db_volume:/app/db_data
      - /Users/justin/LLMS/Contexts/PromptEngineering/:/app/initial_corpus:ro
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite:///./db_data/local_database.sqlite
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  pdf_storage:
  sqlite_db_volume:
  vector_db_volume:
