version: '3.8'
services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - pdf_storage:/app/data/pdfs
      - db_volume:/app/db_data
      - ${INITIAL_CORPUS_PATH}:/app/initial_corpus:ro
      - vector_db_volume:/app/data/vector_store  # ChromaDB storage
    ports:
      - "0.0.0.0:8000:8000"  # Bind to all interfaces for Tailscale access
    environment:
      - DB_URL=sqlite:///./db_data/local_database.sqlite
    depends_on:
      - llm-service

  llm-service:
    image: ollama/ollama:latest
    ports:
      - "0.0.0.0:11434:11434"  # Bind to all interfaces for Tailscale access
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:80"  # Bind to all interfaces for Tailscale access
    depends_on:
      - backend
volumes:
  pdf_storage:
  vector_db_volume:
  ollama_data:
  db_volume: